"""atualizando tabela user

Revision ID: 2df33a258d25
Revises: 262f2f080151
Create Date: 2024-01-07 22:04:51.163698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df33a258d25'
down_revision: Union[str, None] = '262f2f080151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('user', 'is_activate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_activate', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
